name = "novel-search"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "novel-search-db"
database_id = "4b702223-a213-4db3-9365-4b31b6fef0d0"
